export interface Product {
  id: number;
  name: string;
  category: string;
  price: number;
  description: string;
  images: string[];
  dimensions: string;
  material: string;
  details: string[];
}

export interface ProductVariant {
  productId: number;
  color: string;
  colorHex: string;
}

export const variantGroups: Record<string, ProductVariant[]> = {
  'figurine-kaws-monde': [
    { productId: 31, color: 'Noir', colorHex: '#1a1a1a' },
    { productId: 32, color: 'Gris', colorHex: '#9e9e9e' },
    { productId: 33, color: 'Brun', colorHex: '#8B5E3C' },
  ],
};

export function getVariantGroup(productId: number): ProductVariant[] | null {
  for (const group of Object.values(variantGroups)) {
    if (group.some((v) => v.productId === productId)) return group;
  }
  return null;
}

export const products: Product[] = [
  // ── Bubble Blanc ─────────────────────────────────────────────────────────────
  {
    id: 2,
    name: 'Fauteuil Bubble blanc',
    category: 'Salon',
    price: 713,
    description: 'Le Fauteuil Bubble en version blanc immaculé — une silhouette sculpturale aux formes généreuses et organiques. Confort enveloppant, esthétique contemporaine, présence forte dans tout intérieur.',
    images: [
      'https://i.ibb.co/Fk1YZvkY/IMG-2568.jpg',
      'https://i.ibb.co/NdBTdp4B/IMG-2567.jpg',
      'https://i.ibb.co/tPsrFXWs/IMG-2566.jpg',
    ],
    dimensions: 'L 95 × P 90 × H 82 cm',
    material: 'Tissu structuré, base laquée',
    details: ['Forme sculpturale en modules gonflés', 'Tissu résistant haute qualité', 'Base laquée blanc mat', 'Livraison en blanc incluse'],
  },
  {
    id: 10,
    name: 'Canapé Bubble blanc',
    category: 'Salon',
    price: 1857,
    description: 'Le Canapé Bubble 3 places en blanc crème immaculé — silhouette sculpturale et enveloppante, tissu bouclé doux au toucher. Une pièce maîtresse qui transforme instantanément votre salon.',
    images: [
      'https://i.ibb.co/wZRJYt6F/IMG-5364.jpg',
      'https://i.ibb.co/mV8MC19X/IMG-2541.jpg',
    ],
    dimensions: 'L 220 × P 105 × H 80 cm',
    material: 'Tissu bouclé, base laquée',
    details: ['Forme sculpturale en modules gonflés', 'Tissu bouclé doux haute résilience', 'Base laquée blanc mat', 'Livraison en blanc incluse'],
  },
  // ── Bubble Bleu ──────────────────────────────────────────────────────────────
  {
    id: 6,
    name: 'Fauteuil Bubble bleu',
    category: 'Salon',
    price: 713,
    description: 'Le Fauteuil Bubble dans un bleu Klein intense et vibrant — une déclaration artistique autant qu\'une invitation au confort absolu. Texture unique en maille 3D structurée.',
    images: [
      'https://i.ibb.co/gFctkCc0/IMG-2554.jpg',
      'https://i.ibb.co/Z1HkzsfN/IMG-2553.jpg',
      'https://i.ibb.co/x8LZvMgv/IMG-2565.jpg',
    ],
    dimensions: 'L 95 × P 90 × H 82 cm',
    material: 'Tissu maille 3D, base laquée',
    details: ['Forme sculpturale en modules gonflés', 'Tissu maille 3D haute résilience', 'Base laquée bleu nuit', 'Livraison en blanc incluse'],
  },
  {
    id: 13,
    name: 'Canapé Bubble bleu',
    category: 'Salon',
    price: 1857,
    description: 'Le Canapé Bubble 3 places en bleu Klein intense — une présence sculpturale et chromatique forte. Texture maille 3D signature, assise généreuse et enveloppante.',
    images: [
      'https://i.ibb.co/R1tJYDf/IMG-2491.jpg',
      'https://i.ibb.co/tMbZ7D3Y/IMG-0586.jpg',
    ],
    dimensions: 'L 225 × P 105 × H 80 cm',
    material: 'Tissu maille 3D, base laquée',
    details: ['Forme sculpturale en modules gonflés', 'Tissu maille 3D haute résilience', 'Base laquée bleu nuit', 'Livraison en blanc incluse'],
  },
  // ── Bubble Rouge ─────────────────────────────────────────────────────────────
  {
    id: 8,
    name: 'Fauteuil Bubble rouge',
    category: 'Salon',
    price: 713,
    description: 'Le Fauteuil Bubble dans un rouge vif et audacieux — énergie, caractère et confort sculptural réunis. Une pièce iconique qui s\'impose dès le premier regard dans votre salon.',
    images: [
      'https://i.ibb.co/7Jc2Rvd8/IMG-5360.jpg',
      'https://i.ibb.co/Cs8CPTX4/IMG-2558.jpg',
      'https://i.ibb.co/5XbbZ7DH/IMG-2563.jpg',
    ],
    dimensions: 'L 95 × P 90 × H 82 cm',
    material: 'Tissu maille 3D, base laquée',
    details: ['Forme sculpturale en modules gonflés', 'Tissu maille 3D haute résilience', 'Base laquée rouge mat', 'Livraison en blanc incluse'],
  },
  {
    id: 22,
    name: 'Canapé Bubble rouge',
    category: 'Salon',
    price: 1857,
    description: 'Le Canapé Bubble 3 places en rouge vif et ardent — énergie, caractère et confort sculptural. Une pièce iconique qui s\'impose avec force dans votre espace de vie.',
    images: [
      'https://i.ibb.co/zH4qtJVB/IMG-2511.jpg',
      'https://i.ibb.co/Kx5RnfCy/IMG-2542.jpg',
    ],
    dimensions: 'L 225 × P 105 × H 80 cm',
    material: 'Tissu maille 3D, base laquée',
    details: ['Forme sculpturale en modules gonflés', 'Tissu maille 3D haute résilience', 'Base laquée rouge mat', 'Livraison en blanc incluse'],
  },
  // ── Bubble Violet ────────────────────────────────────────────────────────────
  {
    id: 12,
    name: 'Canapé Bubble violet spécial',
    category: 'Salon',
    price: 1857,
    description: 'Le Canapé Bubble 3 places dans un violet prune intense et vibrant — une édition spéciale aux proportions généreuses. Texture maille 3D unique, confort sculptural signature.',
    images: [
      'https://i.ibb.co/My8fK90B/IMG-2525.jpg',
      'https://i.ibb.co/yBk1BSq4/IMG-2659.jpg',
      'https://i.ibb.co/DfjGtFm8/IMG-2526.jpg',
    ],
    dimensions: 'L 230 × P 105 × H 80 cm',
    material: 'Tissu maille 3D, base laquée',
    details: ['Édition spéciale coloris prune', 'Tissu maille 3D haute résilience', 'Base laquée violet mat', 'Livraison en blanc incluse'],
  },
  // ── Bubble Vert ──────────────────────────────────────────────────────────────
  {
    id: 7,
    name: 'Fauteuil Bubble vert',
    category: 'Salon',
    price: 713,
    description: 'Le Fauteuil Bubble dans un vert pistache lumineux — douceur organique et présence végétale. Même confort sculpturale signature, dans une teinte qui renouvelle l\'intérieur.',
    images: [
      'https://i.ibb.co/0pnzSpFV/IMG-2557.jpg',
      'https://i.ibb.co/nMm0vSZz/IMG-2552.jpg',
      'https://i.ibb.co/99RwzY1n/IMG-2534.jpg',
    ],
    dimensions: 'L 95 × P 90 × H 82 cm',
    material: 'Tissu maille 3D, base laquée',
    details: ['Forme sculpturale en modules gonflés', 'Tissu maille 3D haute résilience', 'Base laquée vert mat', 'Livraison en blanc incluse'],
  },
  // ── Bubble Orange ────────────────────────────────────────────────────────────
  {
    id: 9,
    name: 'Fauteuil Bubble orange',
    category: 'Salon',
    price: 713,
    description: 'Le Fauteuil Bubble dans un orange soleil audacieux — même silhouette sculpturale, même confort enveloppant, avec une couleur qui illumine instantanément votre intérieur.',
    images: [
      'https://i.ibb.co/xQ4XWSy/IMG-2530.jpg',
      'https://i.ibb.co/mCyQ2HWm/IMG-2560.jpg',
      'https://i.ibb.co/Jwd6qRVm/IMG-2559.jpg',
    ],
    dimensions: 'L 95 × P 90 × H 82 cm',
    material: 'Tissu structuré, base laquée',
    details: ['Forme sculpturale en modules gonflés', 'Tissu résistant haute qualité', 'Base laquée orange mat', 'Livraison en blanc incluse'],
  },
  // ── Autres produits ──────────────────────────────────────────────────────────
  {
    id: 1,
    name: 'Canapé Élysée',
    category: 'Salon',
    price: 2890,
    description: 'Un canapé d\'exception en tissu bouclé crème, à la structure en chêne massif huilé. Lignes épurées, assise généreuse, coussins à plumes. La pièce maîtresse de votre salon.',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=80',
      'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=900&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80',
    ],
    dimensions: 'L 240 × P 95 × H 78 cm',
    material: 'Tissu bouclé, chêne massif',
    details: ['Pieds en chêne massif huilé', 'Coussins à plumes et duvet', 'Tissu bouclé haute résistance', 'Livraison en blanc incluse'],
  },
  {
    id: 3,
    name: 'Lit Vendôme',
    category: 'Chambre',
    price: 3200,
    description: 'Tête de lit capitonnée en velours doux, structure en hêtre massif laqué blanc. Une présence architecturale dans votre chambre, alliant douceur et raffinement.',
    images: [
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=900&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80',
      'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=900&q=80',
    ],
    dimensions: '160 × 200 cm (disponible en 180 × 200)',
    material: 'Velours, hêtre massif',
    details: ['Tête de lit capitonnée surpiquée', 'Sommier à lattes inclus', 'Structure en hêtre massif laqué', 'Pieds réglables en hauteur'],
  },
  {
    id: 4,
    name: 'Table à manger Opéra',
    category: 'Salle à manger',
    price: 1890,
    description: 'Table à manger en chêne massif huilé avec rallonges intégrées discrètes. Pieds sculpturaux en V. Accueille 6 à 8 convives avec élégance.',
    images: [
      'https://images.unsplash.com/photo-1449247709967-d4461a6a6103?w=900&q=80',
      'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=900&q=80',
      'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=900&q=80',
      'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=900&q=80',
    ],
    dimensions: 'L 200 × P 95 × H 76 cm',
    material: 'Chêne massif huilé',
    details: ['Chêne massif huilé naturel', 'Rallonges intégrées (+50 cm)', 'Pieds en V sculptés à la main', 'Traitement anti-taches inclus'],
  },
  {
    id: 5,
    name: 'Bibliothèque Haussmann',
    category: 'Bureau',
    price: 2100,
    description: 'Bibliothèque ouverte en métal noir mat et étagères en noyer. Structure industrielle affinée, idéale pour structurer un intérieur contemporain.',
    images: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&q=80',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=900&q=80',
      'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=900&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=900&q=80',
    ],
    dimensions: 'L 120 × P 35 × H 200 cm',
    material: 'Métal laqué, noyer massif',
    details: ['Structure métal laqué époxy', 'Étagères en noyer massif', '5 niveaux modulables', 'Fixation murale optionnelle'],
  },
  {
    id: 11,
    name: 'Armoire Versailles',
    category: 'Chambre',
    price: 2750,
    description: 'Armoire à portes coulissantes avec miroir intégré, intérieur personnalisable en chêne naturel. Élégance fonctionnelle pour votre chambre.',
    images: [
      'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=900&q=80',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=900&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&q=80',
    ],
    dimensions: 'L 200 × P 60 × H 220 cm',
    material: 'Chêne naturel, miroir',
    details: ['Portes coulissantes silencieuses', 'Miroir pleine longueur intégré', 'Intérieur modulable (tiroirs, cintres)', 'Finition chêne naturel huilé'],
  },
  {
    id: 14,
    name: 'Tête de lit Madeleine',
    category: 'Chambre',
    price: 890,
    description: 'Tête de lit capitonnée en velours côtelé, surpiquée à la main en motif chevron. Un détail architectural fort pour magnifier votre chambre.',
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80',
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=900&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80',
      'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=900&q=80',
    ],
    dimensions: 'L 160 × H 120 cm (160 ou 180)',
    material: 'Velours, bois massif',
    details: ['Capitonnage surpiqué main', 'Motif chevron signature', 'Structure en bois massif', 'Fixation murale incluse'],
  },
  {
    id: 15,
    name: 'Table Montmartre',
    category: 'Salle à manger',
    price: 1350,
    description: 'Table ronde de cuisine en béton ciré et pieds tripode en acier noir. Robuste et sculpturale, elle s\'intègre aussi bien dans une cuisine qu\'une salle à manger.',
    images: [
      'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=900&q=80',
      'https://images.unsplash.com/photo-1449247709967-d4461a6a6103?w=900&q=80',
      'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=900&q=80',
      'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=900&q=80',
    ],
    dimensions: 'Ø 120 × H 75 cm',
    material: 'Béton ciré, acier',
    details: ['Plateau en béton ciré traité', 'Pieds tripode en acier noir mat', 'Traitement anti-rayures', 'Fond anti-dérapant'],
  },
  {
    id: 16,
    name: 'Table de chevet Pigalle',
    category: 'Chambre',
    price: 490,
    description: 'Chevet asymétrique en noyer et laiton, tiroir coulissant silencieux. Un équilibre parfait entre fonctionnalité et esthétique pour votre chambre.',
    images: [
      'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=900&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80',
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=900&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80',
    ],
    dimensions: 'L 45 × P 38 × H 55 cm',
    material: 'Noyer, laiton',
    details: ['Noyer massif huilé naturel', 'Tiroir en laiton brossé', 'Prise USB intégrée (option)', 'Vendu à l\'unité ou en paire'],
  },
  {
    id: 17,
    name: 'Canapé Riviera',
    category: 'Terrasse',
    price: 1850,
    description: 'Canapé d\'extérieur en résine tressée anthracite, coussins imperméables en tissu Sunbrella®. Pour prolonger votre art de vivre en plein air.',
    images: [
      'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=900&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80',
    ],
    dimensions: 'L 210 × P 90 × H 72 cm',
    material: 'Résine tressée, tissu Sunbrella®',
    details: ['Résine tressée UV-résistante', 'Coussins Sunbrella® imperméables', 'Structure aluminium anti-corrosion', 'Housse de protection incluse'],
  },
  {
    id: 18,
    name: 'Chaise Palais Royal',
    category: 'Salle à manger',
    price: 420,
    description: 'Chaise de salle à manger en bois de hêtre courbé et assise cannée. Un hommage à la tradition française, légère et élégante.',
    images: [
      'https://images.unsplash.com/photo-1581428982868-e410dd047a90?w=900&q=80',
      'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=900&q=80',
      'https://images.unsplash.com/photo-1529489457571-f64aac8e2b5b?w=900&q=80',
      'https://images.unsplash.com/photo-1449247709967-d4461a6a6103?w=900&q=80',
    ],
    dimensions: 'L 48 × P 52 × H 85 cm (assise 46)',
    material: 'Hêtre courbé, cannage',
    details: ['Hêtre courbé à la vapeur', 'Assise cannée artisanale', 'Finition laquée blanche ou noire', 'Vendue à l\'unité ou par lot de 4'],
  },
  {
    id: 19,
    name: 'Fauteuil Bastille',
    category: 'Bureau',
    price: 1680,
    description: 'Fauteuil de bureau en cuir pleine fleur cognac, base en aluminium brossé. Ergonomique et luxueux, il transforme votre bureau en espace de prestige.',
    images: [
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=900&q=80',
      'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=900&q=80',
      'https://images.unsplash.com/photo-1581428982868-e410dd047a90?w=900&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&q=80',
    ],
    dimensions: 'L 70 × P 70 × H 88–98 cm',
    material: 'Cuir pleine fleur, aluminium',
    details: ['Cuir pleine fleur tanné naturel', 'Base 5 étoiles en aluminium brossé', 'Hauteur réglable', 'Accoudoirs réglables'],
  },
  {
    id: 20,
    name: 'Miroir Châtelet',
    category: 'Décoration',
    price: 650,
    description: 'Grand miroir en rotin naturel tressé, format arche. Il apporte chaleur et profondeur à n\'importe quelle pièce, du couloir à la chambre.',
    images: [
      'https://images.unsplash.com/photo-1572544052944-0c4f611e9b2c?w=900&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80',
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=900&q=80',
    ],
    dimensions: 'L 70 × H 160 cm',
    material: 'Rotin naturel, miroir',
    details: ['Cadre en rotin tressé main', 'Miroir anti-déformant 5 mm', 'Forme arche signature', 'Fixation murale ou sur pied (option)'],
  },
  {
    id: 21,
    name: 'Lit Double Étoile',
    category: 'Chambre',
    price: 2600,
    description: 'Lit double à plateforme basse en noyer massif, lignes très épurées. L\'élégance dans sa forme la plus minimaliste pour une chambre zen.',
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80',
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=900&q=80',
      'https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=900&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80',
    ],
    dimensions: '180 × 200 cm (160 × 200 dispo)',
    material: 'Noyer massif',
    details: ['Noyer massif huilé naturel', 'Plateforme basse 25 cm au sol', 'Rangement sous le lit optionnel', 'Tête de lit discrète intégrée'],
  },
  {
    id: 23,
    name: 'Tabouret Élégance',
    category: 'Salon',
    price: 310,
    description: 'Tabouret en velours texturé rose poudré, pieds en laiton doré. Polyvalent : bout de lit, assise d\'appoint, repose-pieds.',
    images: [
      'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=900&q=80',
      'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=900&q=80',
      'https://images.unsplash.com/photo-1529489457571-f64aac8e2b5b?w=900&q=80',
      'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=900&q=80',
    ],
    dimensions: 'Ø 45 × H 40 cm',
    material: 'Velours, laiton',
    details: ['Velours texturé haute densité', 'Pieds en laiton doré', 'Rembourrage mousse haute résilience', 'Disponible en 6 coloris'],
  },
  {
    id: 24,
    name: 'Meuble TV Champs-Élysées',
    category: 'Salon',
    price: 1290,
    description: 'Meuble TV en chêne clair, portes cannelées coulissantes, pieds effilés. Un design scandinave revisité à la française pour habiller votre salon.',
    images: [
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=900&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80',
      'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=900&q=80',
    ],
    dimensions: 'L 160 × P 42 × H 52 cm',
    material: 'Chêne clair, cannage',
    details: ['Chêne massif huilé naturel', 'Portes cannelées coulissantes', 'Passages câbles discrets', 'Pieds en acier laqué noir'],
  },
  {
    id: 25,
    name: 'Lampe Molière',
    category: 'Salon',
    price: 780,
    description: 'Lampadaire arc en marbre blanc et bras articulé en laiton, abat-jour en soie naturelle. Fonctionnel et sculptural, il éclaire et décore à la fois.',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=900&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80',
    ],
    dimensions: 'H 180 cm, bras 140 cm de portée',
    material: 'Marbre, laiton, soie',
    details: ['Base en marbre blanc naturel', 'Bras articulé en laiton massif', 'Abat-jour en soie naturelle', 'Variateur de lumière intégré'],
  },
  {
    id: 26,
    name: 'Étagère Sorbonne',
    category: 'Bureau',
    price: 390,
    description: 'Étagère murale en chêne massif, supports invisibles en acier traité. S\'installe seule ou en composition pour créer un mur de bibliothèque unique.',
    images: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=900&q=80',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=900&q=80',
      'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=900&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=900&q=80',
    ],
    dimensions: 'L 80 × P 25 × H 4 cm',
    material: 'Chêne massif, acier',
    details: ['Chêne massif finition naturelle', 'Supports invisibles inclus', 'Charge max 25 kg', 'Disponible en 3 longueurs'],
  },
  {
    id: 27,
    name: 'Coiffeuse Joséphine',
    category: 'Chambre',
    price: 1100,
    description: 'Coiffeuse avec miroir tri-faces, tiroirs garnis de velours, tablette éclairante LED. Votre espace beauté pensé avec soin et raffinement.',
    images: [
      'https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=900&q=80',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80',
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=900&q=80',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80',
    ],
    dimensions: 'L 110 × P 48 × H 140 cm',
    material: 'Laque blanche, velours, verre',
    details: ['Miroir tri-faces réglables', 'Éclairage LED naturel intégré', 'Tiroirs gainés de velours', 'Tabouret assorti inclus'],
  },
  {
    id: 28,
    name: 'Canapé Invalides',
    category: 'Salon',
    price: 1750,
    description: 'Canapé convertible rapide en tissu chiné gris, matelas mémoire de forme 14 cm. Confort de couchage professionnel dans un design salon élégant.',
    images: [
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=80',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80',
      'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=900&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80',
    ],
    dimensions: 'L 220 × P 95 × H 80 cm (couchage 140 × 190)',
    material: 'Tissu chiné, mousse mémoire',
    details: ['Mécanisme rapide « 3 clics »', 'Matelas mémoire 14 cm', 'Tissu chiné anti-boulochage', 'Coffre de rangement intégré'],
  },
  {
    id: 29,
    name: 'Tabouret Lafayette',
    category: 'Salle à manger',
    price: 280,
    description: 'Tabouret de bar en simili cuir ivoire, structure en métal noir mat. Sobre, élégant, empilable — idéal pour les cuisines ouvertes et les îlots.',
    images: [
      'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=900&q=80',
      'https://images.unsplash.com/photo-1529489457571-f64aac8e2b5b?w=900&q=80',
      'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=900&q=80',
      'https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=900&q=80',
    ],
    dimensions: 'Ø 38 × H 75 cm',
    material: 'Simili cuir, métal',
    details: ['Simili cuir haute résistance', 'Structure métal noir mat soudée', 'Repose-pieds chromé intégré', 'Patins protecteurs sol inclus'],
  },
  {
    id: 30,
    name: 'Salon Extérieur Luxembourg',
    category: 'Terrasse',
    price: 3100,
    description: 'Salon de jardin complet en aluminium thermolaqué blanc, coussins en tissu Sunbrella® écru. L\'élégance du salon intérieur portée en plein air.',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=900&q=80',
      'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=900&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80',
    ],
    dimensions: 'Table Ø 90, canapé 2 pl. L 160, 2 fauteuils',
    material: 'Aluminium, tissu Sunbrella®',
    details: ['Aluminium thermolaqué blanc', 'Coussins Sunbrella® imperméables', 'Table plateau verre trempé', 'Housses de protection incluses'],
  },
  // ── Figurines KAWS Monde ─────────────────────────────────────────────────────
  {
    id: 31,
    name: 'Figurine KAWS noir monde',
    category: 'Figurines',
    price: 75,
    description: 'Figurine KAWS édition Monde en coloris noir intense — une pièce collector incontournable. Sculpture en vinyle premium, finition mate impeccable, 28 cm de hauteur.',
    images: [
      'https://i.ibb.co/r1YNwbR/IMG-0657.jpg',
    ],
    dimensions: 'H 28 cm',
    material: 'Vinyle premium',
    details: ['Édition Monde collector', 'Vinyle premium finition mate', 'Hauteur 28 cm', 'Livraison soigneusement emballée'],
  },
  {
    id: 32,
    name: 'Figurine KAWS gris monde',
    category: 'Figurines',
    price: 75,
    description: 'Figurine KAWS édition Monde en coloris gris — subtilité et caractère dans une même pièce. Sculpture en vinyle premium, finition soyeuse, 28 cm de hauteur.',
    images: [
      'https://i.ibb.co/dss1k9Yf/IMG-0626.jpg',
    ],
    dimensions: 'H 28 cm',
    material: 'Vinyle premium',
    details: ['Édition Monde collector', 'Vinyle premium finition soyeuse', 'Hauteur 28 cm', 'Livraison soigneusement emballée'],
  },
  {
    id: 33,
    name: 'Figurine KAWS brun monde',
    category: 'Figurines',
    price: 75,
    description: 'Figurine KAWS édition Monde en coloris brun chaleureux — une teinte rare et raffinée. Sculpture en vinyle premium, finition naturelle, 28 cm de hauteur.',
    images: [
      'https://i.ibb.co/WvDJ6BCH/IMG-0658.jpg',
    ],
    dimensions: 'H 28 cm',
    material: 'Vinyle premium',
    details: ['Édition Monde collector', 'Vinyle premium finition naturelle', 'Hauteur 28 cm', 'Livraison soigneusement emballée'],
  },
  // ── Figurine KAWS Noir (de face + profil) ────────────────────────────────────
  {
    id: 34,
    name: 'Figurine Kaws noir (28 cm)',
    category: 'Figurines',
    price: 75,
    description: 'Figurine KAWS en coloris noir intense — pièce collector incontournable. Sculpture en vinyle premium, finition mate impeccable, 28 cm de hauteur.',
    images: [
      'https://i.ibb.co/rfHJgML3/IMG-0625.jpg',
      'https://i.ibb.co/s9x78xz3/IMG-0665.jpg',
    ],
    dimensions: 'H 28 cm',
    material: 'Vinyle premium',
    details: ['Édition collector', 'Vinyle premium finition mate', 'Hauteur 28 cm', 'Livraison soigneusement emballée'],
  },
  // ── Bearbrick x Bape ─────────────────────────────────────────────────────────
  {
    id: 35,
    name: 'Bearbrick x Bape (28 cm)',
    category: 'Figurines',
    price: 150,
    description: 'Bearbrick x A Bathing Ape — collaboration iconique entre deux géants du streetwear et du art toy. Pièce collector en vinyle premium, finition impeccable, 28 cm de hauteur.',
    images: [
      'https://i.ibb.co/212j4PLX/IMG-0662.jpg',
    ],
    dimensions: 'H 28 cm',
    material: 'Vinyle premium',
    details: ['Collaboration Bearbrick × Bape', 'Vinyle premium finition mate', 'Hauteur 28 cm', 'Livraison soigneusement emballée'],
  },
];
